sudo: false
install: true
language: java
addons:
  apt:
    packages:
      - fonts-ipafont
      - language-pack-ja
env:
    global:
        - LANG="ja_JP.UTF-8"
        - LC_ALL="ja_JP.UTF-8"
        - TZ="Asia/Tokyo"
script:
  - jdk_switcher use oraclejdk7
  - export JAVA7_HOME=$JAVA_HOME
  - jdk_switcher use oraclejdk8
  - mvn clean verify -Dmaven.javadoc.skip=true -Dgpg.skip=true "-Djdk.7.rt.jar.path=$JAVA7_HOME/jre/lib/rt.jar"
cache:
  directories:
    - $HOME/.m2
